/*Then we make all our normal users participants*/
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'101','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'102','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'103','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'104','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'105','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'106','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'107','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'108','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'109','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'110','302')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'111','302')


/*Then we make the administrator an administrator*/
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'110','303')

/*Then we make the manager and the administrator a manager*/
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'111','301')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'110','301')

/*Finally we add all our users to their organisation groups*/
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'101','201')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'102','202')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'103','203')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'104','204')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'105','205')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'106','206')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'107','207')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'108','208')
INSERT INTO PUBLIC.JBPM_ID_MEMBERSHIP VALUES (NULL,'M',NULL,NULL,'109','209')